name: Sync Repository

on:
  push:
    branches:
      - main # 或者您想要同步的分支

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3

    - name: Remove CNAME file
      run: |
        if [ -f "CNAME" ]; then
          git rm --cached CNAME
          git commit -m "Remove CNAME file"
        fi

    - name: Set up Git
      run: |
        git config --global user.name "maajie"
        git config --global user.email "majieln@qq.com"
        git remote add destination "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/maajie/baidu.git"
        git fetch destination

    - name: Sync to destination repository
      run: |
        git push destination --all --force
      continue-on-error: true # 这将允许步骤失败但工作流程继续

    - name: Check for errors
      if: ${{ failure() }}
      run: |
        echo "An error occurred during the sync process."
        exit 1
